[theme]
base = "dark"
primaryColor = "#5aaee6"
backgroundColor = "#0d131d"
secondaryBackgroundColor = "#141c2a"
textColor = "#e6ebf3"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false